### ISSUE TITLE
OpTomo (python) doesn't support projections with only one angle

### ISSUE THREAD

**Issue by Obi-Wan** [astra-toolbox/astra-toolbox#111]
The python OpTomo implementation throws an error when used with a projection geometry that only projects to a single angle, while this feature would be useful with custom SART algorithms.

Code to reproduce:

```
import numpy as np

import astra

vol_shape = (100, 100)
angles = np.deg2rad(np.linspace(0, 363, 180, endpoint=False))

vol_geom = astra.create_vol_geom(vol_shape)
proj_geom = [astra.create_proj_geom('parallel', 1, vol_shape[0], (a, )) for a in angles]

proj_id = [astra.create_projector('linear', pg, vol_geom) for pg in proj_geom]
W = [astra.OpTomo(p_id) for p_id in proj_id]
```

**Comment by wjp** [comment]
The cause seems to be that in the `Config` struct produced by `CParallelProjectionGeometry2D::toConfiguration()` the distinction between an angle and a list of angles has been lost. We might have to slightly change the `Config` format to preserve this.

**Comment by dmpelt** [comment]
I looked at this problem a while ago. If I remember correctly, the problem is indeed the fact that a list with a single angle is interpreted as a single value, which causes the problems. At the moment I was working on a branch that replaced XML with JSON, which fixed the problem automatically, but in the end I did not create a PR for that. For now it is probably easier to simply catch this special case and fix it. I'm not sure what the best way to do this is though.

**Comment by wjp** [comment]
Since we only use vectors and matrices in configuration files for numbers (both ints and floats), we can probably use the approach of using a trailing comma to indicate a one-element vector (like for python tuples). I'll implement and test this.
