### ISSUE TITLE
Python plugin interface bug

### ISSUE THREAD

**Issue by meetaig** [astra-toolbox/astra-toolbox#155]
Hi,
I am trying to get my own modified variant of SIRT working and am building on top of the SIRT plugin provided with the Python files. I want to give a callable as one of the arguments for the configuration. But it seems that custom classes get converted into their string representation instead of being passed through as actual Python objects.
I set up the algorithm like this:
    `algo_cfg = astra.astra_dict(MyPlugin.astra_name)`
    `algo_cfg['ProjectorId'] = proj_id`
    `algo_cfg['ReconstructionDataId'] = rec_id`
    `algo_cfg['ProjectionDataId'] = sino_id`
    `algo_cfg['option'] = {}`
    `algo_cfg['option']['mycallable'] = mycallable`

but when I look in the `initialize()` method using the PyCharm debugger, all I get passed is a string like:
    `{str}'<MyCallable object at 0x7fbc81260e80>'`

Of course I could try to pickle the classes and load from within the plugin or just send a configuration of the custom class through. But it would be much more versatile if ASTRA didn't try to parse the objects by itself.

Is that something that can be fixed or is planned to be fixed?

edit:
I fiddled around with it a bit more. Passing the configuration of my callable as a Python dictionary results in an empty string being passed to the plugin for the corresponding key. Is that wanted behavior? Passing it to the subdictionary `'option'` even gives:
`terminate called after throwing an instance of 'astra::StringUtil::bad_cast'
  what():  std::exception`

**Comment by dmpelt** [comment]
Hi!

Indeed, passing a Python callable as an option likely won't work... Unfortunately, this is mainly due to the way the ASTRA configuration is set up at the moment, and will be difficult to properly fix without changing this entirely, which would take a lot of time. The problem is that all options are put in an XML format, which is then parsed by the ASTRA C++ code, which means that only things like strings and numbers can be passed in the `astra_dict` object. 

One hacky fix for this at the moment would be to pass the full Python name of the callable as a string inside the `astra_dict` (e.g. `'numpy.zeros'` for the `zeros` callable of `numpy`), and then in the Python plugin code, import the correct module (using `importlib` and possibly some string splitting to get the correct module to import), and finally call the callable (using `getattr`). This requires that the Python plugin code can find the module to import, so maybe some `sys.path` manipulation is required as well.

If there are any problems with this, please let me know -- maybe there is some other way to make this work...

**Comment by wjp** [comment]
One other potential solution would be to expose the python object reference, via something like this:

```
algo_cfg = astra.astra_dict(MyPlugin.astra_name)
algo_cfg['ProjectorId'] = proj_id
algo_cfg['ReconstructionDataId'] = rec_id
algo_cfg['ProjectionDataId'] = sino_id

alg_id = astra.algorithm.create(algo_cfg)
alg_obj = astra.algorithm_get_python_object(alg_id)
alg_obj.set_callable(mycallable)
```

**Comment by meetaig** [comment]
Thanks for your suggestions! I am not quite sure how one would go about implementing the solution @wjp proposed. As for the `importlib` solution, that should indeed work. But as my custom class has a state that I would like to preserve, I opted for `pickle`ing the object and then passing the filename of the `pickle`. This works just fine. I would happily help implementing a more general and less hacky solution.

**Comment by wjp** [comment]
I added a function `astra.algorithm.get_plugin_object` in 0d06afc38d7a8443a079d25d72ec4b4b15353974.

**Comment by meetaig** [comment]
Thank you for that! That will make working with the plugin interface much nicer for me
