### ISSUE TITLE
 error: token ""__CUDACC_VER__ is no longer supported.

### ISSUE THREAD

**Issue by AnderBiguri** [astra-toolbox/astra-toolbox#163]
When compiling ASTRA 1.8 (downloaded from the main page) on Ubuntu with CUDA V9.1.85 (MATLAB 2017b but probably not relevant) I get the following error:

```
/usr/local/cuda/include/crt/common_functions.h:64:24: error: token ""__CUDACC_VER__ is no longer supported.  Use __CUDACC_VER_MAJOR__, __CUDACC_VER_MINOR__, and __CUDACC_VER_BUILD__ instead."" is not valid in preprocessor expressions
 #define __CUDACC_VER__ "__CUDACC_VER__ is no longer supported.  Use __CUDACC_VER_MAJOR__, __CUDACC_VER_MINOR__, and __CUDACC_VER_BUILD__ instead."
```
This seems to be related to the CUDA version. 

Is this expected behavior? Is it only related to my CUDA version? Do I need to isntall an old CUDA version to make ASTRA work?

I assume this has the solution if you need it fixing:

https://stackoverflow.com/questions/50648671/how-do-i-convert-a-cudacc-ver-value-into-a-major-minor-build-triplet

**Comment by pierrepaleo** [comment]
I had a similar problem when compiling on Debian 9.

It seems to be caused by the Boost library being [incompatible with CUDA 9](https://github.com/cms-sw/cmsdist/issues/3583). The problem was [fixed](https://github.com/boostorg/config/pull/175) in Boost 1.65.1. 
Unfortunately, this version is not available yet in the Debian 9 stable (stretch) repositories.

A workaround is to temporarily replace the file "nvcc.hpp" with [the one from 1.6.5](https://github.com/boostorg/config/blob/fixes/1.65/include/boost/config/compiler/nvcc.hpp).
