### ISSUE TITLE
Numpy 1.16 compatible conda version

### ISSUE THREAD

**Issue by adler-j** [astra-toolbox/astra-toolbox#195]
It is currently impossible to install ASTRA and tensorflow at the same time, since tensorflow requires numpy==1.16, while ASTRA requires numpy<1.16.0a0.

Is there any chance that you could release a new build for the new numpy version?

**Comment by wjp** [comment]
Sure. Assuming there are no unexpected build problems, I can build new packages tomorrow.

**Comment by adler-j** [comment]
In case someone else runs into this problem, I've found that the latest versions that are actually runnable are:

```
conda install -c astra-toolbox/label/dev astra-toolbox
pip install tensorflow-gpu=1.7
```

**Comment by wjp** [comment]
@adler-j Are there any specific cudatoolkit version requirements for tensorflow too?

**Comment by adler-j** [comment]
The precompiled tensorflow 1.13 requires CUDA 10.

**Comment by wjp** [comment]
Always an exciting adventure to see which python/numpy/cuda/... combinations are still available on conda. Anyway, I've uploaded a set of linux-64 packages now, including for numpy 1.16 and cudatoolkit 10.0.

**Comment by adler-j** [comment]
I guess there is no way to script this to make it possible to release "all the versions"?

**Comment by wjp** [comment]
It's already scripted, but the playing field keeps changing... (So clearly my script isn't flexible enough... :-) )

I suppose I could make it loop over all cuda, python and numpy version combinations, and build whichever environments conda manages to resolve and skip any failures. Due to the libastra/astra-toolbox split, the combinatorial explosion here is at least somewhat contained.

Combinations regularly fail due to weird reasons (such as broken scipy packages, or numpy/python combinations disappearing for a few months and re-appearing later), but maybe that's not such a big problem for dev builds.

**Comment by wjp** [comment]
Actually, I should also properly read up on numpy ABI compatibility. The numpy ABI (as opposed to the API) has been stable for quite some time, so maybe we don't need such a granular numpy dependency at all.
