### ISSUE TITLE
Confusing behaviour for 3D volumes.

### ISSUE THREAD

**Issue by pwrasmuss** [astra-toolbox/astra-toolbox#206]
Hello,

I am a bit confused by the way the 3D version of `astra.create_vol_geom()` works. As I understand it takes the dimensions Y, X, Z or rows, columns, slices. However, a volume initialised with with Y, X, Z will return (Z, Y, X) when `astra.functions.geom_size(vol_geom)` is used. This also means it cannot be used to create a 3D data object with an array with the dimensions Y, X, Z. I have included a minimal working example below which returns the error:

```python
import numpy as np
import astra

num_rows, num_cols, num_slices = 3, 4, 5
vol_geom = astra.create_vol_geom(num_rows, num_cols, num_slices)
print("astra.functions.geom_size(vol_geom) = ", astra.functions.geom_size(vol_geom))
empty_data = np.zeros((3, 4, 5))
test = astra.data3d.create('-vol', vol_geom, empty_data)
```

```python
Traceback (most recent call last):

  File "<ipython-input-1-fd41a80954b6>", line 8, in <module>
    test = astra.data3d.create('-vol', vol_geom, empty_data)

  File "/home/superuser/anaconda3/envs/tomopy/lib/python3.6/site-packages/astra/data3d.py", line 43, in create
    return d.create(datatype,geometry,data)

  File "astra/data3d_c.pyx", line 163, in astra.data3d_c.create

  File "astra/data3d_c.pyx", line 243, in astra.data3d_c.fillDataObject

ValueError: The dimensions of the data do not match those specified in the geometry: (3, 4, 5) != (5, 3, 4)
```

Kind regards,
Peter

**Comment by meetaig** [comment]
Hi,
I think there are two effects in play here. The Y, X, Z order is correct, so that part of your code should be exactly like that. But when you print the size of the array you might notice that it prints in order Z, Y, X. I assume this is due to the convention of numpy (and also MATLAB) of specifying the last dimension as the contiguous memory dimension, not the first, as it is usually done in languages like C. 
When populating the volume geometry it fills in `SliceCount, RowCount then ColCount`. But it prints it in the order `RowCount, ColCount, SliceCount` in `data3d.get()`. Which is how you have to define the numpy array shape, if you want to have the code run without crashing.

I don't know if this is a bug or just a confusing convention. @wjp what do you think?

**Comment by jttoombs** [comment]
I'm having the same problem. I cannot seem to comprehend how the axes are defined...

**Comment by pwrasmuss** [comment]
They describe the ordering in [https://github.com/astra-toolbox/astra-toolbox/blob/master/samples/python/s006_3d_data.py](url). Basically volumes are defined by (y, x, z) while arrays used for initialization are defined as (z, y, x).
