### ISSUE TITLE
Installation problem: Boost and CUDA versions are incompatible.

### ISSUE THREAD

**Issue by alperelli** [astra-toolbox/astra-toolbox#237]
Hi, I am building the Astra toolbox, on a machine without root privileges. I have installed automake, boost... locally. 

While I call configure as follow
./configure --prefix=$HOME/.local/lib CXXFLAGS=-I$HOME/.local/boost-libs/include LDFLAGS=-L$HOME/.local/boost-libs/lib --with-cuda=/opt/cuda/cuda-10.0 --with-matlab=/opt/apps/matlab/r2018b --with-python --prefix=$HOME/astra --with-install-type=module

I obtain the error:
configure: error: Boost and CUDA versions are incompatible. You probably have to upgrade boost.

CUDA version: 10.0
GCC version: 7.5.0
BOOST version: 1.65.1 (or 1.69 or 1.73)

I wonder if the parameters for configure are wrong or something else.

Thanks you in advance.

**Comment by tblattner** [comment]
Spent an hour dealing with this exact issue. I install everything in my home directory without root (including CUDA toolkit and boost). Because of this the test for checking Boost and CUDA versions does not find the path to boost, as shown in the code below.

https://github.com/astra-toolbox/astra-toolbox/blob/2952c1baa69beb7a53aba002055a73c784ae8fe3/build/linux/acinclude.m4#L169

So to fix I added this to my configure:

NVCCFLAGS=-I/path/to/boost/include CPPFLAGS=-I/path/to/boost/include LDFLAGS=-L/path/to/boost/lib ./configure --with-cuda=/usr/local/cuda-10.0 --with-matlab=/path/to/MATLAB/R2020b --prefix=/path/to/home/local --with-install-type=module

Granted this was for compiling for MATLAB, but may help here.
