### ISSUE TITLE
Weird Artifact with SIRT Cone Beam

### ISSUE THREAD

**Issue by Scriptkiddi** [astra-toolbox/astra-toolbox#299]
When generating a SIRT reconstruction with a cone beam geometry
I get artifacts on the sides, as can been seen here:
![image](https://user-images.githubusercontent.com/3598650/130080021-b5edc3f6-ea0a-4178-867c-372cbc12cb24.png)
Using the TIGRE library with the same parameters they do not show:
![image](https://user-images.githubusercontent.com/3598650/130080179-911eef49-9655-4354-84ae-eed830a6f11c.png)
Any ideas why?

**Comment by juanenofbit** [comment]
This artifact problem is similar to the one presented in issue #297.
It seems that the reconstruction methods available for cone-beam geometry, which need to use the CUDA GPU operators, are getting strange artifacts.

Although cone-beam CT with circular path does not meet the Tuy condition (accurate reconstruction of a plane requires the plane to contain the X-ray focal point), these artifacts appears to be due to an implementation problem.

**Comment by Scriptkiddi** [comment]
@wjp why was this closed?

**Comment by wjp** [comment]
Maybe I misinterpreted the discussion above, but it seemed to me that juanenofbit above described the likely difference in algorithm behind this.

ASTRA does have the option of a non-negativity constraint in SIRT3D_CUDA too, by the way, using `cfg['option']['MinConstraint'] = 0` (python syntax) or `cfg.option.MinConstraint = 0;` (matlab syntax).
