### ISSUE TITLE
How to install astra without cuda 

### ISSUE THREAD

**Issue by Olin1461** [astra-toolbox/astra-toolbox#364]
Hi,

I try to install astra on a mac computer without cuda. How I change the configuration if I use "conda install -c astra-toolbox astra-toolbox" to install?

Thanks!

**Comment by askorikov** [comment]
Hi! I imagine the command you mention should just work. Or do you encounter some specific problem when running that?

**Comment by Olin1461** [comment]
Sorry that I did not state my problem clearly. I can install astra using this command line but I cannot run astra because I do not have gpu that supports cuda on my computer. So should I install a version of astra which can be used on computer without cuda or should I specify something when I use astra?

THanks!

**Comment by askorikov** [comment]
I see. You can use astra without CUDA with your installation without changing anything, you just need to avoid using `_CUDA` versions of algorithms. This would also mean that you can only use 2D algorithms, because the rest is not implemented on CPU, but if your geometry is parallel, you can implement 3D methods in a slice-by-slice way.

**Comment by Olin1461** [comment]
Get it. Thanks for your help!
