### ISSUE TITLE
BP3D-CUDA memory requirements estimation

### ISSUE THREAD

**Issue by dkazanc** [astra-toolbox/astra-toolbox#476]
Hi, would it be possible to approximately estimate the GPU memory requirements for BP3D-CUDA function? 
It [uses](https://github.com/astra-toolbox/astra-toolbox/blob/51561150bbc5d4ebc8f7a715e4c539542a5a5eb0/cuda/3d/par3d_bp.cu#L241C7-L241C52) Texture memory, so  I guess it is not that straightforward? 

In the framework that we develop we need to know precisely how much memory is required to avoid OOM CUDA. We use the experimental `astra.data3d.GPULink` which I guess making the streaming feature inactive? 

many thanks!

**Comment by askorikov** [comment]
Hi! In this situation (if input and output are already allocated and provided via GPULink), you would need to ensure that you have roughly a `volume_size` of GPU memory available. That is because Astra needs to copy the linear memory provided via GPUlink to a cudaArray to be able to use texture fetching.

**Comment by askorikov** [comment]
Sorry, I just realized that you were asking about backprojection. In that case, it should be `sinogram_size` of additional GPU memory required.

**Comment by dkazanc** [comment]
Thanks for the reply @askorikov.
While trying to estimate it purely heuristically by looking at  `nvidia-smi` output we came to that formula for the required memory:
```
in_data_size = np.prod(input_data_dims) * dtype.itemsize
out_data_size = np.prod(output_data_dims) * dtype.itemsize
astra_projection = 2.5 * (in_data_size + out_data_size)
```
This 2.5 multiplier is heuristic and not very accurate, however going slightly lower results in OOM CUDA error. As you can see, it is rather a significant amount of memory needed to perform the operation.  As we work with pretty big volumes, we need those estimations to be pretty accurate, but it is OK for us to overestimate the memory a bit.

**Comment by askorikov** [comment]
That sounds about right, but I was expecting the memory requirements to be a bit lower. Can you maybe paste in the part of the code where you allocate your data and pass it to Astra so that I can look at it in the debugger?

**Comment by dkazanc** [comment]
thanks @askorikov!
I was using this [function ](https://github.com/dkazanc/ToMoBAR/blob/54137829b6326406e09f6ef9c95eb35c213838a7/tomobar/methodsDIR_CuPy.py#L87) which can be executed through this [test](https://github.com/dkazanc/ToMoBAR/blob/54137829b6326406e09f6ef9c95eb35c213838a7/tests/test_RecToolsDIRCuPy.py#L236). 
I should have mentioned that I use GPULink functionality and passing  a  pointer to CuPy array. The code is [here](https://github.com/dkazanc/ToMoBAR/blob/54137829b6326406e09f6ef9c95eb35c213838a7/tomobar/astra_wrappers/astra_base.py#L491). Potentially that makes some difference compared to the normal way of CUDA built Astra function.

**Comment by wjp** [comment]
Hi Daniil, Alex is correct that if you allocate the input and output arrays yourself via CuPy and pass them to astra via GPULink, then the extra GPU memory requirements on top of that should be equal to the input size. So total requirements are twice input size plus once output size. (Plus some minor stuff that would be very hard to quantify exactly.)

I can't immediately think of any reason why it would take this much more, but I'll try to run things through ToMoBAR to see if anything pops up.

By the way, if you want a more convenient interface for cupy-based backprojection, the function `astra.experimental.direct_BP3D` takes a projector_id and GPULink structs for both input and output directly. (We should probably move it out of the `experimental` module by now though...)

As an aside, we should also really think about how to make FP3D and BP3D work for this GPULink case without risking OOM's. I'll give this some serious thought in the near future, because it's definitely kind of bad for interoperability with other GPU software.

**Comment by wjp** [comment]
Uh oh, I hadn't actively realized that `BP3D_CUDA` still accepts the `GPUindex` option, because I think that hasn't actually been used anymore for quite some time (for 3D, specifically). Currently if you don't globally set the GPU index using `astra.set_gpu_index`, then `BP3D_CUDA` and `FP3D_CUDA` will use the currently selected GPU context.

IIRC cupy has the same behaviour when creating arrays, so that should mean the GPULink'ed arrays end up on the same device too. So I hope that means that even without that option astra does what you need. Please let me know if you do need more configurability on the astra side here.

Sorry about the confusion. I'll have to spend some time going through this to add warnings if the GPUIndex option is set but not used.

**Comment by dkazanc** [comment]
thanks @askorikov and @wjp for help and clarification about the usage of the GPUindex. We are updating our part to the (experimental) API mentioned. This can be closed therefore. Cheers.
