### ISSUE TITLE
Make the OpTomo class be pickle-able

### ISSUE THREAD

**Issue by AurysSilinga** [astra-toolbox/astra-toolbox#480]
**Is your feature request related to a problem? Please describe.**
I would like to use functools.lru_cashe to speed up repeated calls of a function that takes an instance of astra.optomo.OpTomo as a parameter.  The OpTomo class cannot be pickled, therefore this fails.

**Describe the solution you'd like**
The error is caused by the source code lines: 
```
from . import data2d
from . import data3d

....

self.data_mod = data2d
self.data_mod = data3d
```

*Solution*
data2d and data3d should be redefined as classes instead of modules, because modules are not pickle-able in python.

**Describe alternatives you've considered**
I can use the volume as and projection geometries as parameters to reinitalise the OpTomo object with every call, but it would be more convenient to pickle the whole object.

Edit: This also prevents any object that contains an instance of OpTomo from pickling. Pickling would be useful for saving data in a convenient way.

**Comment by askorikov** [comment]
Hi! I can't quite reproduce this. As far as I understand, `lru_cache` should work as long as the object is hashable, which works with the current implementation. For pickling, we could indeed consider the change you propose, but the problem is that it still wouldn't be "real" serialization, because the projector is not pickled (and it's not easy to implement this). I would be in favor of having projection and volume geometry as the arguments of `OpTomo` (instead of projector ID), which should make everything serializable, but that would be an API-breaking change.
